<?php
/**
 * @file
 * The functions for the Mailrelay Statistics module.
 */
 
function mailrelay_statistics_menu() {
  $items = array();
  $items['admin/config/services/mailrelay/statistics'] = array(
    'title' => 'Statistics',
    'page callback' => 'mailrelay_statistics_page',
    'access arguments' => array('administer content'),
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/config/services/mailrelay/statistics/general'] = array(
    'title' => 'General',
    'page callback' => 'mailrelay_statistics_page',
    'access arguments' => array('administer content'),
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/services/mailrelay/statistics/location'] = array(
    'title' => 'Location',
    'page callback' => 'mailrelay_statistics_page_location',
    'access arguments' => array('administer content'),
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
    'file' => 'mailrelay_statistics_location.inc',
  );
  $items['admin/config/services/mailrelay/statistics/technology'] = array(
    'title' => 'Technology',
    'page callback' => 'mailrelay_statistics_page_technology',
    'access arguments' => array('administer content'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
    'file' => 'mailrelay_statistics_technology.inc',
  );
  return $items;
}

function mailrelay_statistics_form($form, &$form_state) {
  $mailinglists = mailrelay_newsletterslist_getMailingListsData();
  $options = array();
  foreach ($mailinglists as $row) {
    $options[$row->id] = $row->subject;
  }

  $path = current_path();
  preg_match("/[^\/]+$/", $path, $matches);
  $lastword = $matches[0];
  if (is_numeric($lastword)) {
    $mid = $lastword;
  }
  elseif (variable_get('mailrelay_statistics_value', '')) {
    $mid = variable_get('mailrelay_statistics_value', '');
  }
  else {
    $mid = '';
  }

  $form['mailinglists'] = array(
    '#title' => 'Newsletters List',
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => $mid,
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

function mailrelay_statistics_form_submit($form, &$form_state) {
  variable_set('mailrelay_statistics_value', $form_state['values']['mailinglists']);
}

function mailrelay_statistics_page() {
  if (!variable_get('mailrelay_hostname') == 0) {

  $render_form = drupal_get_form('mailrelay_statistics_form');
  $curl = curl_init('http://' . variable_get('mailrelay_hostname', '') . '/ccm/admin/api/version/2/&type=json');

  if (variable_get('mailrelay_statistics_value', '')) {
    $mid = variable_get('mailrelay_statistics_value', '');
  }
  else {
    $mid = arg(5);
  };

  $postdata = array(
    'function' => 'getStats',
    'apiKey' => variable_get('mailrelay_api_key', ''),
    'id' => $mid
  );

  curl_setopt($curl, CURLOPT_POST, TRUE);
  curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($postdata));
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

  $json = curl_exec($curl);
  $result = json_decode($json);
  $general_statistics = $result->data;

  if ($mid) {
    foreach ($general_statistics as $key => $value) {
      $key = ucwords(str_replace('_', ' ', $key));
      $rows[] = array(t($key), $value);
      $gs_type[] = array(t($key));
      $gs_quantity[] = array($value);
    }

    drupal_add_js('https://www.google.com/jsapi', 'external');
    drupal_add_js(array(
      'mailrelay_statistics' =>
        array(
          'gs_type' => $gs_type,
          'gs_quantity' => $gs_quantity,
          'gs_table' => $rows
        )
      ),
      array('type' => 'setting')
    );
    drupal_add_js(drupal_get_path('module', 'mailrelay_statistics') . '/js/statistic_general.js');
    $data = array(
      '#type' => 'markup',
      '#prefix' => '<div id="general">',
      '#markup' => '<h2>' . t('General') . '</h2>',
      '#suffix' => '</div>',
    );
    $output = array($render_form, $data);
    return $output;
  }
  else {
    return $render_form;
  }
  }
  else {
    $message = drupal_set_message(t('Register a Hostname and API Key'), 'error');
    $message .= drupal_goto('admin/config/services/mailrelay');
    return $message;
  }
}